platform :ios, '11.0'
use_frameworks!

target 'AMZLocationManager_Example' do
  pod 'AMZLocationManager', :path => '../'
  pod 'AppmazoUIKit'
  pod 'AMZAlertController'

  target 'AMZLocationManager_Tests' do
    inherit! :search_paths

    
  end
end
